/* ============================================================
   VIGIL — systems/domestic-content.js
   Procedural content generation for domestic (US soil) threats.
   Org names, intel values, feed descriptions for homeland
   surveillance operations.
   ============================================================ */

// --- Domestic Location Generation ---
// Filters THEATERS.NORTH_AMERICA.cities for US-only locations.

function generateDomesticLocation() {
  var theater = THEATERS.NORTH_AMERICA;
  var usCities = [];
  for (var i = 0; i < theater.cities.length; i++) {
    if (theater.cities[i].country === 'United States') {
      usCities.push(theater.cities[i]);
    }
  }
  var city = pick(usCities);
  return {
    theater: theater,
    theaterId: theater.id,
    city: city.city,
    country: city.country,
    lat: city.lat,
    lon: city.lon,
  };
}

// --- Domestic Organization Name Generation ---
// Keyed by domestic threat type ID. Each pool contains 50+ names.

var DOMESTIC_ORG_NAMES = {
  DOMESTIC_EXTREMISM: [
    'Sovereign Shield Militia',
    'Patriots of the New Order',
    'Liberty Vanguard Movement',
    'American Reclamation Front',
    'Oath of Iron Brotherhood',
    'True Republic Defenders',
    'Heartland Resistance Corps',
    'Freedomwatch Militia',
    'Sons of the Covenant',
    'Continental Guard Alliance',
    'Patriot Sentinel Network',
    'Wolverine State Militia',
    'Defenders of the Constitution',
    'Republic Restoration Project',
    'National Liberty Front',
    'Appalachian Freedom Brigade',
    'Minuteman Revival Corps',
    'Heritage First Coalition',
    'The Gadsden Collective',
    'American Valor Movement',
    'Iron Eagle Militia',
    'Constitutional Guardsmen',
    'Frontier Defense League',
    'Sovereign Citizens Brigade',
    'The Bonfire Patriots',
    'Three Percent Vanguard',
    'Mountain Republic Militia',
    'Redoubt Defense Network',
    'Liberty Bell Alliance',
    'Sons of the Plains',
    'Crossroads Militia',
    'Silent Majority Front',
    'American Resolute Movement',
    'Ozark Sovereignty Militia',
    'Cascadian Patriots',
    'The Sentinel Order',
    'Prairie Fire Resistance',
    'Constitutional Vanguard Society',
    'Old Glory Defenders',
    'Timberline Militia',
    'Piedmont Liberty Corps',
    'Keystone Resistance League',
    'Bayou Freedom Militia',
    'High Desert Sovereigns',
    'The Cottonmouth Brigade',
    'Northern Star Militia',
    'Rattlesnake Ridge Patriots',
    'Lone Star Resistance Front',
    'Great Basin Defenders',
    'Allegheny Freemen Militia',
    'Eagle Rock Sovereignty Movement',
    'Badlands Patriot Corps',
    'The Granite State Irregulars',
    'Cumberland Gap Defense League',
    'Palmetto Patriots Militia',
    'Blue Ridge Resistance',
    'Tidewater Sovereignty Alliance',
    'Sagebrush Rebellion Militia',
  ],
  FINANCIAL_CRIME: [
    'Meridian Capital Holdings',
    'Cascade Wire Group',
    'Pinnacle Fiduciary Partners',
    'Bridgewater Equity Associates',
    'Granite Point Financial LLC',
    'Keystone Venture Consortium',
    'Tidewater Asset Management',
    'Redline Capital Networks',
    'Atlas Sovereign Trust',
    'Ironbridge Holdings Group',
    'Whitfield & Chambers LLP',
    'Cerulean Harbor Capital',
    'Northwind Equity Partners',
    'Sterling Gate Investments',
    'Crescent Bay Fiduciary Corp',
    'Hawthorne Wealth Advisors',
    'Pacific Rim Capital Group',
    'Silverleaf Asset Holdings',
    'Blackstone River Ventures',
    'Olympus Financial Services',
    'Ridgewood Capital Advisors',
    'Belmont Trust Corporation',
    'Cardinal Point Investments',
    'Sovereign Crest Holdings',
    'Dalton Marsh & Associates',
    'Foxhaven Capital Group',
    'Granite Peak Equity LLC',
    'Highland Crest Financial',
    'Ivory Tower Capital Partners',
    'Juniper Creek Holdings',
    'Lakeshore Venture Partners',
    'Montrose Capital Advisors',
    'Nautical Mile Investments',
    'Obsidian Rock Holdings',
    'Primrose Wealth Management',
    'Quarry Hill Capital Corp',
    'Redwood Basin Financial',
    'Sandstone Bridge Partners',
    'Thornfield Asset Group',
    'Upperline Capital LLC',
    'Vanguard Shore Investments',
    'Westbrook Fiduciary Trust',
    'Yellowstone Capital Partners',
    'Zenith Point Holdings',
    'Archer Lane Financial',
    'Bayview Trust Associates',
    'Clarendon Capital Group',
    'Dunmore Asset Management',
    'Edgewater Wealth Partners',
    'Falcon Ridge Equity LLC',
    'Glenmore Capital Holdings',
    'Harbor Point Financial Corp',
    'Ironstone Wealth Advisors',
    'Kensington Capital Trust',
  ],
  CYBER_INTRUSION: [
    'Phantom Circuit',
    'Null Sector',
    'GhostRail Collective',
    'ShadowMesh',
    'Darkwater Protocol',
    'Voidcrypt',
    'ZeroBreach',
    'Iron Proxy',
    'Deadlink Syndicate',
    'CipherStorm',
    'BinaryFront',
    'NetSpectre',
    'BlackNode Collective',
    'SilkThread',
    'RootHive',
    'Oblivion Gate',
    'DarkPulse',
    'BytePhantom',
    'WireWraith',
    'HexLayer',
    'NullRoute Collective',
    'CryptFog',
    'RedPacket',
    'SilentSocket',
    'Malware Bazaar Crew',
    'DarkForge',
    'OverflowKings',
    'PacketStorm',
    'BitShade Syndicate',
    'GhostRAT Collective',
    'SubZero Crew',
    'Kernel Panic',
    'DeepSocket',
    'VoltEdge',
    'EchoWall',
    'Blackout Protocol',
    'RazorNet',
    'BleachBit Brigade',
    'TorchByte',
    'NightCrawler Ops',
    'QuantumRust',
    'SpiderProxy',
    'IronShell Collective',
    'DriftNet',
    'StaticNoise',
    'ZeroDay Merchants',
    'DarkTracer',
    'Rootkit Syndicate',
    'HollowByte',
    'GlitchForge',
    'ShadowStack',
    'CipherHound',
    'NullVector',
    'PhreakShow',
    'Backbone Syndicate',
    'MaskNet Collective',
    'Payload Kings',
    'ExploitChain',
  ],
  INSIDER_THREAT: [
    'SUBJECT CARDINAL',
    'SUBJECT LANCER',
    'SUBJECT KEYSTONE',
    'SUBJECT DRIFTWOOD',
    'SUBJECT PINECONE',
    'SUBJECT MARBLE',
    'SUBJECT REDTAIL',
    'SUBJECT IRONSIDE',
    'SUBJECT CHAPEL',
    'SUBJECT GREENFIELD',
    'SUBJECT FALCON',
    'SUBJECT BRIARWOOD',
    'SUBJECT COMPASS',
    'SUBJECT RIDGEWAY',
    'SUBJECT OAKLEAF',
    'SUBJECT SPARROW',
    'SUBJECT FLINTLOCK',
    'SUBJECT WEATHERVANE',
    'SUBJECT COBALT',
    'SUBJECT TINDERBOX',
    'SUBJECT SANDPIPER',
    'SUBJECT GRANITE',
    'SUBJECT BRAMBLE',
    'SUBJECT CROSSBOW',
    'SUBJECT FOXHOUND',
    'SUBJECT LIMESTONE',
    'SUBJECT PENNANT',
    'SUBJECT RIMFIRE',
    'SUBJECT SNOWBIRD',
    'SUBJECT TURNSTILE',
    'SUBJECT ANVIL CREEK',
    'SUBJECT BELLHAVEN',
    'SUBJECT COPPERFIELD',
    'SUBJECT DIAMONDBACK',
    'SUBJECT EVERGLADES',
    'SUBJECT FROSTLINE',
    'SUBJECT GRYPHON',
    'SUBJECT HARBORLIGHT',
    'SUBJECT IVYWOOD',
    'SUBJECT JUNIPER',
    'SUBJECT KINGFISHER',
    'SUBJECT LARKSPUR',
    'SUBJECT MILLSTONE',
    'SUBJECT NIGHTHAWK',
    'SUBJECT OSPREY',
    'SUBJECT PATCHWORK',
    'SUBJECT QUARTZITE',
    'SUBJECT RIDGERUNNER',
    'SUBJECT SAWGRASS',
    'SUBJECT THORNBERRY',
    'SUBJECT UNDERHILL',
    'SUBJECT VERANDA',
    'SUBJECT WHIPPOORWILL',
    'SUBJECT YARROW',
  ],
  ORGANIZED_CRIME: [
    'Volkov Organization',
    'The Rialto Syndicate',
    'Marchetti Crime Family',
    'Eastshore Triad',
    'The Caspian Network',
    'Dorado Cartel Remnant',
    'Iron Ring Syndicate',
    'Pacific Basin Group',
    'The Novak Consortium',
    'Blackshore Organization',
    'Castellano Crime Family',
    'The Tigris Brotherhood',
    'Belmont Avenue Syndicate',
    'Krasnov Organization',
    'The Jade Circle Triad',
    'Guzman Remnant Network',
    'Sicilian Harbor Syndicate',
    'The Karadzic Network',
    'Southside Commission',
    'The Golden Dragon Tong',
    'Petrov Crime Family',
    'The Crescent Syndicate',
    'Gambino Offshoot Network',
    'Red Phoenix Triad',
    'The Balkan Connection',
    'Morales Distribution Syndicate',
    'Brighton Beach Organization',
    'The Five Points Remnant',
    'Lagos Pipeline Network',
    'Yakuza West Coast Cell',
    'The Adriatic Group',
    'Romani Crime Network',
    'Cantonese Merchants Syndicate',
    'The Odessa Mafia',
    'Calabrian Organization',
    'The Albanian Outfit',
    'Lagos-Houston Pipeline',
    'Corsican Network West',
    'The Moldovan Syndicate',
    'Fujianese Human Trafficking Ring',
    'The Chechen Brotherhood',
    'Colombian Remnant Network',
    'The Armenian Power Organization',
    'Vietnamese Syndicate West',
    'The Georgian Thieves',
    'Dominican Pipeline Syndicate',
    'The Montenegrin Outfit',
    'Haitian Crime Network',
    'The Azeri Connection',
    'Salvadoran Remnant Syndicate',
    'Trinitario Organization',
    'The Bulgarian Mafia',
    'Jamaican Posse Network',
    'The Kosovar Outfit',
  ],
  CIVIL_UNREST: [
    'Free Horizon Coalition',
    'Citizens United Against Surveillance',
    'The Accountability Front',
    'American Liberty Collective',
    'Occupy the Algorithm',
    'People\'s Privacy Alliance',
    'Dismantle the Machine',
    'No More Eyes Movement',
    'Democratic Futures Network',
    'Coalition for Civil Autonomy',
    'Unplug the Panopticon',
    'Transparency Now Coalition',
    'Mass Noncompliance Movement',
    'Rights Reclamation Project',
    'The Digital Resistance',
    'Stop the Watchers Coalition',
    'Citizens for Radical Transparency',
    'The Autonomy Collective',
    'Defund the Apparatus',
    'People\'s Sovereignty Movement',
    'The Firewall Coalition',
    'Workers Against Surveillance',
    'Justice Unfiltered',
    'The Open Curtain Project',
    'Mothers Against State Overreach',
    'Students for Civil Reclamation',
    'The Fourth Amendment Brigade',
    'Abolish the Archive',
    'Neighborhood Sovereignty Coalition',
    'Voices Without Filters',
    'The Oversight Resistance',
    'Tech Workers for Accountability',
    'Dignity Over Data Coalition',
    'Shutdown the Machine Movement',
    'The Consent Collective',
    'Citizens Against Predictive Policing',
    'Reclaim the Commons',
    'The Analog Movement',
    'Unchain Democracy Coalition',
    'Digital Rights Defense Front',
    'The Blackout Collective',
    'People Power Against PRISM',
    'Grassroots Privacy Alliance',
    'The Warrant Requirement Coalition',
    'Teachers Against Mass Surveillance',
    'Veterans for Constitutional Rights',
    'The Due Process Coalition',
    'Resist the Feed Movement',
    'Community Self-Governance Alliance',
    'The Encryption Coalition',
    'Public Accountability Network',
    'The Whistleblower Solidarity Front',
    'Off the Grid Movement',
    'The Right to Vanish Collective',
  ],
  WHISTLEBLOWER: [
    'LEAKER PRISM',
    'CASE CANDLELIGHT',
    'LEAK CORRIDOR',
    'CASE NIGHTJAR',
    'LEAKER FOXGLOVE',
    'CASE UNDERTOW',
    'LEAK MERIDIAN',
    'CASE BELLWETHER',
    'LEAKER SUNDIAL',
    'CASE IRONCLAD',
    'LEAKER WINDFALL',
    'CASE THISTLEDOWN',
    'LEAK TRIBUTARY',
    'CASE LAMPBLACK',
    'LEAKER SAWMILL',
    'CASE RIDGETOP',
    'LEAK SNOWMELT',
    'CASE FIREWEED',
    'LEAKER MILLPOND',
    'CASE TURNPIKE',
    'LEAK FOGHORN',
    'CASE QUARRYSTONE',
    'LEAKER BRAMBLEGATE',
    'CASE DAWNBREAK',
    'LEAK CROSSFIRE',
    'CASE HARBORTIDE',
    'LEAKER PINEWOOD',
    'CASE THUNDERHEAD',
    'LEAK IRONWORK',
    'CASE SALTMARSH',
    'LEAKER COPPERMINE',
    'CASE RIDGELINE',
    'LEAK SANDCASTLE',
    'CASE MOONRISE',
    'LEAKER ASHFIELD',
    'CASE TIDELAND',
    'LEAK FROSTBITE',
    'CASE WILLOWBEND',
    'LEAKER CLOCKTOWER',
    'CASE HEARTHSTONE',
    'LEAK DRIFTNET',
    'CASE SPRINGTIDE',
    'LEAKER GRINDSTONE',
    'CASE WATERSHED',
    'LEAK BLACKTHORN',
    'CASE FIELDSTONE',
    'LEAKER OXBOW',
    'CASE RIMROCK',
    'LEAK TAILWIND',
    'CASE CORNERPOST',
    'LEAKER RAVENSWOOD',
    'CASE MILLRACE',
    'LEAK BREAKWATER',
    'CASE FLINTHILL',
  ],
  CORPORATE_ESPIONAGE: [
    'Nexus Applied Sciences',
    'Aegis Dynamics LLC',
    'Halcyon Research Partners',
    'Vertex Technical Solutions',
    'Parallax Industries',
    'Stratos Engineering Group',
    'Obsidian Analytics Inc.',
    'Helix Consulting International',
    'Meridian Defense Systems',
    'Apex Horizon Technologies',
    'Catalyst Quantum Labs',
    'Vanguard Micro Systems',
    'Prisma Semiconductor Corp',
    'Ironclad Cyber Solutions',
    'Titan Nanotechnologies',
    'Redshift Photonics LLC',
    'Cobalt Integrated Systems',
    'Vector Aerospace Research',
    'Summit AI Partners',
    'Orion Signal Processing',
    'BlueArc Defense Technologies',
    'Spectra Bioengineering',
    'Pinnacle Robotics Group',
    'Fulcrum Data Systems',
    'Cascade Neural Networks Inc.',
    'Atlas Propulsion Labs',
    'Citadel Systems Integration',
    'Eclipse Advanced Materials',
    'Frontier Quantum Computing',
    'Granite Cyber Defense',
    'Hyperion Technical Services',
    'Lighthouse Aerospace Corp',
    'Monolith Semiconductor',
    'Nighthawk Defense Consulting',
    'Overwatch Analytics LLC',
    'Paragon Satellite Systems',
    'Quasar Energy Technologies',
    'Resolute Engineering Partners',
    'Sentinel Data Corp',
    'Trident Marine Systems',
    'Umbra Intelligence Solutions',
    'Valkyrie Propulsion Group',
    'Warden Cybersecurity Inc.',
    'Xenith Materials Science',
    'Yellowstone Research Consortium',
    'Zenith Avionics Group',
    'Aether Communications Corp',
    'Bastion Nuclear Technologies',
    'Cornerstone Directed Energy',
    'Delphi Autonomous Systems',
    'Echelon Signal Intelligence',
    'Forge Advanced Composites',
    'Gridlock Encryption Services',
    'Harbinger Space Technologies',
  ],
  NARCOTICS_NETWORK: [
    'Gulf Corridor Network',
    'Sinaloa Pipeline East',
    'Interstate 10 Supply Chain',
    'Appalachian Distribution Ring',
    'Coastal Fentanyl Network',
    'Rust Belt Heroin Corridor',
    'Southwest Gateway Syndicate',
    'Great Lakes Distribution Cell',
    'Sunbelt Methamphetamine Ring',
    'Pacific Northwest Pipeline',
    'Rio Grande Transit Network',
    'Dixie Highway Distribution Ring',
    'Atlantic Seaboard Pipeline',
    'Midwest Opioid Corridor',
    'Mojave Desert Transit Network',
    'Chesapeake Bay Supply Ring',
    'Carolina Corridor Network',
    'Denver Hub Distribution Cell',
    'Everglades Transit Pipeline',
    'Florida Keys Smuggling Ring',
    'Georgia Corridor Network',
    'Houston Hub Syndicate',
    'Interstate 95 Corridor Ring',
    'Jersey Turnpike Pipeline',
    'Kansas City Distribution Hub',
    'Louisiana Bayou Smuggling Ring',
    'Memphis Transfer Network',
    'Nashville Distribution Cell',
    'Oklahoma Pipeline Ring',
    'Phoenix Gateway Syndicate',
    'Queen City Fentanyl Network',
    'Reno Transit Corridor',
    'San Antonio Hub Network',
    'Tennessee Valley Pill Mill Ring',
    'Utah Corridor Pipeline',
    'Virginia Beach Landing Network',
    'Wichita Transfer Hub',
    'Yuma Crossing Pipeline',
    'Zuni Corridor Ring',
    'Bakersfield Meth Corridor',
    'Columbus Distribution Network',
    'Detroit Supply Chain Ring',
    'El Paso Gateway Pipeline',
    'Fresno Valley Distribution',
    'Gary Industrial Corridor',
    'Hartford Heroin Ring',
    'Indianapolis Hub Network',
    'Jacksonville Transit Pipeline',
    'Knoxville Pill Distribution Ring',
    'Las Vegas Strip Pipeline',
    'Mobile Bay Smuggling Network',
    'Tucson Corridor Syndicate',
    'Twin Cities Distribution Hub',
  ],
  DOMESTIC_TERROR: [
    'Harvest Moon Cell',
    'Black Phalanx',
    'The Seventh Column',
    'Ashfall Network',
    'Pale Horse Cell',
    'Crucible Initiative',
    'Scorched Earth Brigade',
    'Red November Cell',
    'The Covenant Directive',
    'Burning Standard',
    'Iron Dawn Collective',
    'Obsidian Crescent Cell',
    'The Lazarus Network',
    'Wolfpack Cell',
    'Nightshade Initiative',
    'The Furnace Collective',
    'Rust Horizon Cell',
    'Silent Thunder Network',
    'The Gallows Directive',
    'Powder Keg Brigade',
    'Crimson Tide Cell',
    'The Reaper Initiative',
    'Ghost Fire Collective',
    'The Blackthorn Network',
    'Serpent Coil Cell',
    'Molten Core Initiative',
    'The Ivory Fist',
    'Deadfall Network',
    'Eclipse Cell',
    'The Cleansing Fire',
    'Steel Veil Collective',
    'Ragnarok Cell',
    'The Broken Seal',
    'Flashpoint Initiative',
    'Dusk Protocol Cell',
    'The Wormwood Directive',
    'Ember Storm Network',
    'Cold Forge Cell',
    'The Final Trumpet',
    'Hollow Ground Collective',
    'Anvil Strike Cell',
    'The Scarlet Threshold',
    'Deadlight Network',
    'Bone Ash Cell',
    'The Scouring Wind',
    'Midnight Verdict Collective',
    'Tremor Cell',
    'The Iron Scripture',
    'Brimstone Initiative',
    'Carrion Call Network',
    'The Wrath Doctrine',
    'Cinder Vault Cell',
    'Tombstone Directive',
    'The Black Harvest',
    'Phosphorus Cell',
  ],
  HOSTAGE_DOMESTIC: [
    'HOSTAGE INCIDENT ALPHA',
    'HOSTAGE INCIDENT BRAVO',
    'HOSTAGE INCIDENT CHARLIE',
    'HOSTAGE INCIDENT DELTA',
    'HOSTAGE INCIDENT ECHO',
    'HOSTAGE INCIDENT FOXTROT',
    'HOSTAGE INCIDENT GOLF',
    'HOSTAGE INCIDENT HOTEL',
    'HOSTAGE INCIDENT INDIA',
    'HOSTAGE INCIDENT JULIET',
    'HOSTAGE INCIDENT KILO',
    'HOSTAGE INCIDENT LIMA',
    'HOSTAGE INCIDENT MIKE',
    'HOSTAGE INCIDENT NOVEMBER',
    'HOSTAGE INCIDENT OSCAR',
    'HOSTAGE INCIDENT PAPA',
    'HOSTAGE INCIDENT QUEBEC',
    'HOSTAGE INCIDENT ROMEO',
    'HOSTAGE INCIDENT SIERRA',
    'HOSTAGE INCIDENT TANGO',
    'HOSTAGE INCIDENT UNIFORM',
    'HOSTAGE INCIDENT VICTOR',
    'HOSTAGE INCIDENT WHISKEY',
    'HOSTAGE INCIDENT XRAY',
    'HOSTAGE INCIDENT YANKEE',
    'HOSTAGE INCIDENT ZULU',
    'HOSTAGE INCIDENT ANVIL',
    'HOSTAGE INCIDENT BEACON',
    'HOSTAGE INCIDENT COBALT',
    'HOSTAGE INCIDENT DAGGER',
    'HOSTAGE INCIDENT EMBER',
    'HOSTAGE INCIDENT FLINT',
    'HOSTAGE INCIDENT GRANITE',
    'HOSTAGE INCIDENT HAMMER',
    'HOSTAGE INCIDENT IVORY',
    'HOSTAGE INCIDENT JAVELIN',
    'HOSTAGE INCIDENT KEYSTONE',
    'HOSTAGE INCIDENT LIGHTNING',
    'HOSTAGE INCIDENT MAGNET',
    'HOSTAGE INCIDENT NIGHTFALL',
    'HOSTAGE INCIDENT ONYX',
    'HOSTAGE INCIDENT PINNACLE',
    'HOSTAGE INCIDENT QUARRY',
    'HOSTAGE INCIDENT RAPTOR',
    'HOSTAGE INCIDENT SABLE',
    'HOSTAGE INCIDENT TEMPEST',
    'HOSTAGE INCIDENT UNDERTOW',
    'HOSTAGE INCIDENT VORTEX',
    'HOSTAGE INCIDENT WARHAMMER',
    'HOSTAGE INCIDENT ZENITH',
    'HOSTAGE INCIDENT CROSSBOW',
    'HOSTAGE INCIDENT DUSTFALL',
    'HOSTAGE INCIDENT FIRESTORM',
    'HOSTAGE INCIDENT GRYPHON',
    'HOSTAGE INCIDENT IRONCLAD',
  ],
  ASSASSINATION_TARGET: [
    'SUBJECT CROWBAR',
    'SUBJECT ANVIL',
    'SUBJECT GALLOWS',
    'SUBJECT WRAITH',
    'SUBJECT FALCONER',
    'SUBJECT OBSIDIAN',
    'SUBJECT TOMBSTONE',
    'SUBJECT MERIDIAN',
    'SUBJECT BLACKTHORN',
    'SUBJECT VICEROY',
    'SUBJECT RATTLESNAKE',
    'SUBJECT JACKAL',
    'SUBJECT GUILLOTINE',
    'SUBJECT PHANTOM',
    'SUBJECT HEMLOCK',
    'SUBJECT SCORPION',
    'SUBJECT DIREWOLF',
    'SUBJECT CRUCIBLE',
    'SUBJECT HELLFIRE',
    'SUBJECT GAUNTLET',
    'SUBJECT VIPER',
    'SUBJECT STILETTO',
    'SUBJECT WARHAWK',
    'SUBJECT CALDERA',
    'SUBJECT MACHETE',
    'SUBJECT RAPTOR',
    'SUBJECT TREBUCHET',
    'SUBJECT NIGHTSHADE',
    'SUBJECT IRON MAIDEN',
    'SUBJECT PITBULL',
    'SUBJECT CLAYMORE',
    'SUBJECT HARBINGER',
    'SUBJECT VULTURE',
    'SUBJECT SWITCHBLADE',
    'SUBJECT CERBERUS',
    'SUBJECT CLEAVER',
    'SUBJECT SERPENT',
    'SUBJECT FIREBRAND',
    'SUBJECT BARRACUDA',
    'SUBJECT REAPER',
    'SUBJECT WIDOWMAKER',
    'SUBJECT BUTCHER',
    'SUBJECT TALON',
    'SUBJECT MAULER',
    'SUBJECT CROSSHAIR',
    'SUBJECT DREADNOUGHT',
    'SUBJECT RAMPART',
    'SUBJECT TOMAHAWK',
    'SUBJECT BASILISK',
    'SUBJECT SANDSTORM',
    'SUBJECT HATCHET',
    'SUBJECT GRAVEDIGGER',
    'SUBJECT WARLOCK',
    'SUBJECT TYPHOON',
    'SUBJECT COLOSSUS',
  ],
  DOMESTIC_CAPTURE_TARGET: [
    'FUGITIVE IRONGATE',
    'FUGITIVE ASHWOOD',
    'FUGITIVE COPPERHEAD',
    'FUGITIVE RIDGELINE',
    'FUGITIVE TIDEWATER',
    'FUGITIVE HARROWFIELD',
    'FUGITIVE CORNERSTONE',
    'FUGITIVE NIGHTFALL',
    'FUGITIVE STONEBRIDGE',
    'FUGITIVE BLACKWATER',
    'FUGITIVE PINECREST',
    'FUGITIVE REDCLIFF',
    'FUGITIVE THORNWOOD',
    'FUGITIVE SALTFLAT',
    'FUGITIVE MILLBROOK',
    'FUGITIVE DARKHOLLOW',
    'FUGITIVE WHITECAP',
    'FUGITIVE FOXDEN',
    'FUGITIVE IRONBARK',
    'FUGITIVE DUSTTRAIL',
    'FUGITIVE COLDSPRING',
    'FUGITIVE MARSHFIELD',
    'FUGITIVE GREYSTONE',
    'FUGITIVE RAVENCROFT',
    'FUGITIVE SLATECREEK',
    'FUGITIVE BRACKENRIDGE',
    'FUGITIVE DEERFIELD',
    'FUGITIVE HAWKSMOOR',
    'FUGITIVE KETTLEBURN',
    'FUGITIVE LONGMEADOW',
    'FUGITIVE MOSSBANK',
    'FUGITIVE NORTHWIND',
    'FUGITIVE OAKRIDGE',
    'FUGITIVE PEARLHAVEN',
    'FUGITIVE QUARTZHILL',
    'FUGITIVE RIVERSTONE',
    'FUGITIVE SHADOWCREEK',
    'FUGITIVE TIMBERLINE',
    'FUGITIVE UNDERCLIFF',
    'FUGITIVE VALLEYFORGE',
    'FUGITIVE WINDERMERE',
    'FUGITIVE YARMOUTH',
    'FUGITIVE ZINCLODE',
    'FUGITIVE BIRCHWOOD',
    'FUGITIVE CANYONWALL',
    'FUGITIVE DRIFTWOOD',
    'FUGITIVE ELKHORN',
    'FUGITIVE FLINTSTONE',
    'FUGITIVE GOLDFIELD',
    'FUGITIVE HEMLOCKVALE',
    'FUGITIVE JASPERPOINT',
    'FUGITIVE KNOTTWOOD',
    'FUGITIVE LARCHMONT',
    'FUGITIVE MUDRIVER',
    'FUGITIVE NETHERFIELD',
  ],
};

function generateDomesticOrgName(threatType) {
  var pool = DOMESTIC_ORG_NAMES[threatType];
  if (!pool || pool.length === 0) return generateOrgName();
  return pick(pool);
}

// --- Domestic Intel Value Pools ---
// Pools for domestic-specific intel field keys.
// Use {city}, {country}, {orgName} placeholders.

var DOMESTIC_INTEL_VALUE_POOLS = {

  // --- Subject & Cell Identification ---

  SUBJECT_ID: [
    'Vigil facial recognition matched subject to federal watchlist entry. Last known residence: {city}. Employment history indicates prior military service.',
    'Subject identified via PRISM intercept. Social media footprint links to {orgName}. Pattern-of-life analysis underway in {city} metro area.',
    'Biometric match confirmed through TSA screening checkpoint. Subject traveled to {city} 14 times in past 90 days. No declared business purpose.',
    'Subject flagged by Vigil behavioral algorithm during routine financial audit. Multiple cash deposits below reporting threshold in {city} banking institutions.',
    'Identity confirmed via cross-referencing CCTV network in {city} with NSA selector database. Subject uses 3 known aliases.',
    'Vigil has identified subject through metadata analysis of encrypted communications originating from {city}. Real identity pending field confirmation.',
  ],

  CELL_LOCATION: [
    'Vigil geolocation triangulated to a rental property in {city} industrial district. Lease held under shell identity. Surveillance drone deployed.',
    'Primary cell operating from a residential address in eastern {city}. SIGINT confirms encrypted burst transmissions from the location at 0300 local daily.',
    'Safe house identified in suburban {city}, {country}. Cell members rotate between this address and a secondary location near the {city} waterfront.',
    'Commercial property in {city} flagged by Vigil pattern analysis — unusual foot traffic, blacked-out windows, RF emissions inconsistent with declared business.',
    'Cell location confirmed via mobile device geofencing in {city}. Multiple flagged handsets co-located for 6+ hours on 4 consecutive nights.',
  ],

  ONLINE_ACTIVITY: [
    'Vigil web-scraping detected {orgName} recruitment posts on 3 encrypted forums. Language analysis indicates operational planning, not aspirational rhetoric.',
    'Dark web monitoring: subject in {city} purchasing restricted technical manuals. Transaction linked to cryptocurrency wallet with known extremist funding chain.',
    'Social media surveillance flagged subject for escalating radical content sharing. Vigil sentiment analysis rates radicalization trajectory as HIGH.',
    'PRISM intercept: encrypted messaging traffic from {city} shows subject coordinating with 6 unidentified contacts. Message cadence suggests countdown protocol.',
    'Vigil automated content scan flagged video upload from {city} containing coded operational language. Linguistic markers match {orgName} communication patterns.',
    'Dark web forum activity linked to {orgName} increased 400% over 30-day baseline. Multiple posts reference {city} by coded designation.',
  ],

  MEMBERSHIP_ROSTER: [
    'Vigil network analysis identifies 12-15 active members of {orgName}. Inner circle of 4 controls operational planning. Remaining members provide logistics.',
    'Cross-referencing travel records, financial transactions, and communications metadata yields 8 confirmed members with ties to {city}.',
    'Membership roster partially reconstructed from seized digital media. 9 names confirmed. Vigil assesses 3-5 additional members remain unidentified.',
    'Social network mapping via Vigil places {orgName} membership at 18-22 individuals spanning {city} and two adjacent counties.',
    'Informant reporting combined with SIGINT yields 6 positively identified members. Cell structure suggests compartmented teams of 2-3.',
  ],

  WEAPONS_PROCUREMENT: [
    'ATF trace data indicates subject in {city} purchased 7 firearms across 3 states in 60-day period. Straw purchase indicators present.',
    'Vigil financial monitoring flagged bulk purchases of ammonium nitrate by {orgName}-linked entity in {city}. Quantities exceed any legitimate agricultural need.',
    'Dark web transaction log shows subject acquiring detonator components shipped to a {city} P.O. box. Package tracking intercepted.',
    'Surveillance camera network in {city} captured subject transporting weapons cases from a storage unit. Vigil license plate reader confirmed identity.',
    'Undercover ATF source reports {orgName} members attempting to acquire automatic weapons and body armor. Meet location: {city}.',
  ],

  RADICALIZATION_NETWORK: [
    'Vigil algorithmic analysis maps radicalization pathway: subject consumed 200+ hours of extremist content before connecting with {orgName} recruiter in {city}.',
    'Online radicalization network centered on 3 encrypted channels. Administrator traced to {city} via operational security failure. 40+ active participants.',
    'Prison radicalization confirmed: subject recruited into {orgName} ideology during federal incarceration. Post-release, relocated to {city}.',
    'Vigil behavioral profiling identifies subject on accelerated radicalization trajectory. Social isolation metrics and content consumption patterns match pre-attack profiles.',
    'University campus in {city} identified as recruitment pipeline for {orgName}. Vigil monitoring 4 student organizations with overlapping membership.',
  ],

  ATTACK_PLANNING: [
    'SIGINT indicates {orgName} in active target selection phase. Surveillance of 3 soft targets in {city} detected via cell phone location data.',
    'Vigil pattern recognition flagged Google Maps queries from {orgName}-linked device: federal building layouts, security camera positions, guard rotation schedules in {city}.',
    'Source reporting indicates {orgName} operational planning meeting in {city}. Attack timeline assessed at 2-4 weeks. Specific target not yet confirmed.',
    'Intercepted communications reference a date and location in {city}. Vigil assesses HIGH probability of imminent attack. Recommend preemptive action.',
    'Digital forensics from seized device reveal {orgName} reconnaissance photography of critical infrastructure in {city}. Planning stage: advanced.',
  ],

  FINANCING_TRAIL: [
    'Vigil financial intelligence traces $340,000 in suspicious wire transfers to {orgName}-linked accounts in {city}. Funds originated from 7 shell entities.',
    'Cryptocurrency analysis reveals {orgName} funding network utilizing privacy coins laundered through {city}-based exchanges. Total volume: $1.2M over 6 months.',
    'Cash-intensive businesses in {city} identified as {orgName} money laundering fronts. Vigil financial algorithms detected revenue patterns inconsistent with reported business activity.',
    'Foreign wire transfers to subject in {city} flagged by FinCEN. Originator linked to designated foreign terrorist organization. Amount: $85,000 over 4 transfers.',
    'Crowdfunding campaign analysis by Vigil identifies {orgName} soliciting funds under humanitarian cover. $200K+ raised from 1,400 donors.',
  ],

  // --- Insider Threat ---

  ACCESS_LEVEL: [
    'Subject holds TS/SCI clearance with access to VIGIL compartmented programs. Polygraph: last passed 18 months ago. Access logs show after-hours terminal use.',
    'Subject has TOP SECRET clearance with access to intelligence databases. Vigil access monitoring flagged 340% increase in classified document queries.',
    'Subject cleared at SECRET level with physical access to NSA facility in {city}. Badge reader logs show irregular entry patterns.',
    'Subject holds TS/SCI with SAP access. Vigil insider threat algorithm flagged anomalous download patterns from classified networks over 90-day period.',
    'Subject is cleared contractor with network administrator privileges. Root access to 3 classified systems. Vigil behavioral baseline deviation: CRITICAL.',
  ],

  EXFILTRATION_METHOD: [
    'Vigil network monitoring detected unauthorized USB device connections on classified terminal. Data transfer volume: 14GB over 3 sessions.',
    'Subject photographing classified documents with personal mobile device. Vigil facility monitoring captured device emissions in SCIF.',
    'Classified material printed to unmonitored printer during off-hours. Vigil badge-and-print correlation analysis identified subject.',
    'Data exfiltration via steganography embedded in personal email attachments. Vigil deep packet inspection flagged anomalous file characteristics.',
    'Subject using dead-drop protocol in {city}. Physical surveillance confirms regular visits to predetermined location on 14-day cycle.',
  ],

  DATA_COMPROMISED: [
    'Vigil damage assessment: subject accessed 847 classified documents across 12 program areas. Includes SIGINT collection methods and source identities.',
    'Preliminary analysis indicates compromise of satellite reconnaissance capabilities and technical specifications. National security impact: SEVERE.',
    'Classified operational plans for 3 active VIGIL operations accessed without need-to-know. Potential compromise of field assets.',
    'Subject downloaded intelligence community personnel database. Names, clearance levels, and cover identities of 2,300+ intelligence officers potentially exposed.',
    'Assessment ongoing. Confirmed access to weapons system vulnerabilities and cyber operation toolkits. Damage scope may take months to determine.',
  ],

  HANDLER_CONTACT: [
    'SIGINT intercept confirms subject in contact with foreign intelligence officer operating under diplomatic cover in {city}. Meeting frequency: biweekly.',
    'Vigil surveillance captured subject meeting unidentified individual at {city} restaurant. Facial recognition pending. Tradecraft indicators suggest intelligence exchange.',
    'Subject communicating with suspected foreign handler via encrypted messaging application. Vigil metadata analysis identifies handler device in foreign embassy.',
    'Dead-drop communication protocol identified. Subject services location in {city} on alternating Tuesdays. Counter-surveillance employed by both parties.',
    'No foreign handler identified. Subject may be acting independently — motivated by ideology rather than foreign direction. Vigil assessment: lone actor.',
  ],

  // --- Whistleblower / Leak ---

  MOTIVATION_ASSESSMENT: [
    'Vigil psychological profile indicates ideological motivation. Subject has expressed anti-surveillance views on personal devices flagged by monitoring algorithms.',
    'Financial stress indicators: subject in {city} carrying $180K in debt. Vigil assesses vulnerability to recruitment or independent action for financial gain.',
    'Subject exhibits disgruntlement patterns consistent with pre-leak behavioral profile. Recent denied promotion and filed workplace grievance.',
    'Vigil assessment: subject motivated by misguided ethical concerns regarding program legality. Prior complaints to inspector general documented and dismissed.',
    'Mixed motivation assessed: ideological opposition to classified programs combined with narcissistic personality indicators. High media-seeking probability.',
  ],

  DAMAGE_ASSESSMENT: [
    'If published, leaked material would compromise 4 active collection programs and reveal intelligence-sharing agreements with 3 allied nations.',
    'Vigil damage assessment: CRITICAL. Material includes details of domestic surveillance architecture that would trigger congressional investigation and public backlash.',
    'Preliminary assessment: leaked documents reveal classified budget allocations and capability gaps. Adversary exploitation potential: HIGH.',
    'Material compromises sources and methods across 2 intelligence disciplines. 6 field assets in imminent danger if published.',
    'Damage scope: SEVERE. Leaked technical specifications would allow adversaries to develop countermeasures against Vigil monitoring capabilities.',
  ],

  LEAK_CHANNEL: [
    'Vigil traces indicate subject communicating with journalist via SecureDrop instance hosted on overseas infrastructure. 3 document transfers confirmed.',
    'Subject using encrypted email with journalist at major national newspaper. Vigil metadata analysis identified both endpoints despite encryption.',
    'Physical documents mailed via USPS to media organization. Vigil postal monitoring flagged originating ZIP code matching subject\'s {city} address.',
    'Subject uploading material to anonymous file-sharing service. Vigil internet monitoring captured upload signatures matching classified document formatting.',
    'Leak channel identified as personal meeting with journalist in {city}. Vigil CCTV network captured 2 meetings at same location over 30 days.',
  ],

  MEDIA_CONTACTS: [
    'Vigil identifies 2 journalist contacts: national security reporter at major newspaper and an investigative podcast producer. Both based in Washington D.C.',
    'Subject in contact with foreign journalist operating from {city}. Publication history includes classified material from previous leaks.',
    'Media contact identified as freelance investigative journalist with ties to international transparency organizations. Based in {city}.',
    'Multiple media contacts identified via Vigil communications monitoring. Subject has reached out to 4 news organizations simultaneously.',
    'Primary media contact is editor at online investigative outlet known for publishing classified material. Vigil monitors all their encrypted intake channels.',
  ],

  CLASSIFIED_MATERIAL_SCOPE: [
    'Material spans 3 classification levels and 7 compartments. Includes VIGIL operational directives, collection priorities, and automated targeting criteria.',
    'Scope limited to single program area but includes highly sensitive technical details. Documents marked TS/SCI/NOFORN.',
    'Broad scope: subject accessed materials across multiple agencies. Vigil assesses 400-600 documents potentially compromised.',
    'Material includes classified legal opinions authorizing domestic surveillance operations. Political sensitivity: EXTREME.',
    'Scope assessment ongoing. Subject had access to 12 SAP programs over 4-year period. Full damage inventory will require 6-8 weeks.',
  ],

  PUBLISHER_TIMELINE: [
    'Vigil intelligence indicates publication imminent — within 48-72 hours. News organization has contacted government for comment, standard pre-publication protocol.',
    'Timeline assessed at 1-2 weeks. Journalist still conducting verification and seeking additional sources. Window for intervention exists.',
    'Publication timeline unknown. No indicators of imminent release. Subject may be stockpiling material for maximum impact.',
    'Vigil intercept suggests publication timed to coincide with upcoming congressional hearing. Estimated: 10-14 days.',
    'Immediate risk. Material already shared with editorial board. Legal review at news organization is final step before publication.',
  ],

  // --- Civil Unrest ---

  MOVEMENT_LEADERSHIP: [
    'Vigil social network analysis identifies 3 primary organizers of {orgName} in {city}. Profiles compiled from social media, financial records, and communications metadata.',
    'Leadership structure is decentralized — Vigil identifies 6-8 coordinators using encrypted group chats. No single leader. Consensus-based decision making.',
    'Primary organizer identified via Vigil facial recognition at 4 consecutive protest events in {city}. Full dossier compiled.',
    'Movement leadership traced to academic institution in {city}. 2 professors and 1 graduate student identified as ideological core of {orgName}.',
    'Vigil assessment: {orgName} leadership includes former civil rights attorneys and community organizers. Legal sophistication makes infiltration difficult.',
  ],

  PARTICIPANT_ESTIMATE: [
    'Vigil crowd analysis via aerial surveillance and cell tower data estimates 2,500-3,000 participants at {city} demonstration. Growing daily.',
    'Current participation: 800-1,200 active protesters. Vigil social media monitoring indicates mobilization calls could increase to 5,000+ within 48 hours.',
    'Cell tower ping analysis for {city} protest area indicates 4,000-6,000 devices present. Vigil assesses 70% are active participants.',
    'Participation declining: 400-600 at latest event, down from 2,000 peak. Vigil assesses movement may be losing momentum without intervention.',
    'Vigil projects participation surge to 10,000+ for planned march in {city}. Social media amplification by foreign accounts detected.',
  ],

  COMMUNICATIONS_NETWORK: [
    'Vigil monitoring reveals {orgName} using 3 encrypted platforms for coordination: Signal groups, encrypted email lists, and a private forum. 200+ active users.',
    'Communications infrastructure includes pirate radio station broadcasting in {city}, encrypted messaging, and physical flyer distribution network.',
    'Decentralized mesh networking detected at protest sites in {city}. Participants using peer-to-peer apps to coordinate in real-time, bypassing cellular surveillance.',
    '{orgName} operating a VPN-protected coordination hub. Vigil has identified the hosting provider but content remains encrypted. Traffic analysis ongoing.',
    'Movement communications increasingly shifting to in-person meetings and analog methods. Vigil assessment: operational security awareness is improving.',
  ],

  FOREIGN_INFLUENCE: [
    'Vigil social media analysis detects coordinated amplification of {orgName} messaging by accounts linked to foreign state information operations.',
    'No foreign state influence detected. Movement appears to be organically domestic. Vigil continues monitoring for external exploitation.',
    'Financial analysis reveals small donations to {orgName} routed through foreign-registered NGOs. Total: $45,000. State direction: UNCONFIRMED.',
    'Foreign state media providing favorable coverage of {city} protests. Vigil assesses this as opportunistic exploitation rather than directed influence.',
    'SIGINT intercept indicates foreign intelligence service monitoring {orgName} for potential recruitment and exploitation. No active operation confirmed yet.',
  ],

  // --- Escalation & Contingency ---

  ESCALATION_INDICATORS: [
    'Vigil behavioral analysis detects shift in {orgName} rhetoric from political advocacy to operational language. Weapons-related searches flagged on member devices.',
    'Protest events in {city} showing escalation pattern: property damage incidents increased 300% over last 3 events. Counter-protester confrontations reported.',
    'SIGINT indicates {orgName} leadership discussing direct action beyond lawful protest. Specific plans not yet identified. Vigil threat level: ELEVATED.',
    'Vigil monitoring detects bulk purchase of tactical equipment by {orgName} members in {city}. Body armor, gas masks, communication equipment.',
    'No escalation indicators at this time. {orgName} leadership actively promoting nonviolent approach. Vigil maintains monitoring posture.',
  ],

  CONTINGENCY_PLANNING: [
    'Vigil intercepts indicate {orgName} has established backup communication channels and alternative rally points in {city} in case of law enforcement action.',
    '{orgName} legal support network activated: 12 attorneys on standby for mass arrest scenario. Bail fund exceeds $500K. Organization is prepared for confrontation.',
    'Subject has established escape routes and safe house network in {city}. Go-bag identified at primary residence via warrant-authorized search.',
    'Vigil assesses {orgName} has no contingency planning. Organization is reactive and poorly organized. Disruption via leadership targeting would be effective.',
    'Intercepted communications suggest {orgName} has a succession plan: if primary leaders are arrested, 3 designated alternates will assume coordination roles.',
  ],

  // --- Financial Crime ---

  SHELL_COMPANIES: [
    'Vigil financial mapping identifies 14 shell entities linked to {orgName}. Registered across 6 states with overlapping directors and registered agents in {city}.',
    'Corporate registry analysis reveals nested ownership structure: 4 layers of LLCs obscuring beneficial ownership. Primary nexus: {city}, {country}.',
    'Shell company network uses nominee directors sourced from elderly individuals in {city}. Vigil facial recognition confirms nominees have no awareness of their role.',
    '{orgName} operating through 8 shell companies with bank accounts in {city}. Total assets identified: $23M. Legitimate business activity: negligible.',
    'Vigil automated corporate analysis flagged 22 entities registered at same {city} address. All linked to {orgName} financial network.',
  ],

  TRANSACTION_PATTERNS: [
    'Vigil financial monitoring detects structured cash deposits across 9 banks in {city}. Each under $10,000 reporting threshold. Total: $2.3M over 90 days.',
    'Wire transfer analysis shows circular payment patterns: funds moving through {orgName} entities and returning to origin within 72 hours. Classic layering.',
    'Unusual real estate transactions in {city}: 6 properties purchased at above-market prices by {orgName}-linked entities. Assessed as money laundering.',
    'Vigil algorithm flagged {orgName} for invoice fraud: fabricated invoices between shell companies generating $4.7M in apparent revenue with no goods or services exchanged.',
    'Cryptocurrency transaction monitoring reveals {orgName} converting $800K monthly through mixing services. Destination wallets linked to overseas accounts.',
  ],

  BENEFICIAL_OWNERS: [
    'Vigil investigation identifies ultimate beneficial owner as a foreign national residing in {city} under assumed identity. Biometric confirmation pending.',
    'Beneficial ownership traced to 3 individuals: 2 US citizens in {city} and 1 foreign national. All maintain low public profiles.',
    'Corporate veil penetrated: {orgName} controlled by single individual using 4 aliases. Real identity confirmed via Vigil biometric database.',
    'Beneficial ownership deliberately obscured through trust structures and nominee arrangements. Vigil assesses 2-3 principal controllers. Identification ongoing.',
    'Primary beneficial owner identified via leaked financial documents cross-referenced with Vigil tax records. Subject resides in {city}.',
  ],

  MONEY_LAUNDERING_CHAIN: [
    'Laundering chain: cash collection in {city} > structuring across regional banks > wire to shell entities > real estate investment > clean funds returned.',
    'Three-stage laundering operation: placement via cash-intensive businesses in {city}, layering through international wire transfers, integration via luxury goods purchases.',
    '{orgName} using trade-based money laundering: over-invoicing imports through {city} port. Differential retained in offshore accounts.',
    'Vigil traces complete laundering cycle: illicit funds enter through {city} casino operations, transferred to shell accounts, invested in commercial real estate.',
    'Hawala-based laundering network operating from {city}. $5-10M monthly volume. Funds ultimately integrated into legitimate investment portfolios.',
  ],

  // --- Narcotics ---

  SUPPLY_CHAIN: [
    'Vigil interdiction analysis maps supply chain: production in Mexico, transit through {city} corridor, distribution across 4 Midwestern states.',
    'Fentanyl precursors traced from Chinese chemical suppliers to Mexican labs to {orgName} distribution hub in {city}. DEA coordination requested.',
    'Supply chain disrupted at {city} node but {orgName} rerouting through secondary corridor. Adaptation time: estimated 72 hours.',
    '{orgName} controlling full vertical supply chain from border crossing to street-level distribution in {city}. Estimated annual revenue: $80M.',
    'Maritime supply route identified: bulk shipments arriving at {city} port concealed in commercial cargo. Vigil port monitoring flagged 3 suspicious containers.',
  ],

  DISTRIBUTION_NETWORK: [
    'Vigil street-level mapping identifies 22 distribution points across {city}. {orgName} using rotating stash houses and burner phone networks.',
    'Distribution network spans {city} metro area: 4 mid-level distributors, 15-20 street dealers. Vigil phone tree analysis maps complete hierarchy.',
    '{orgName} using ride-share vehicles for distribution in {city}. Vigil license plate readers and GPS tracking identify 8 vehicles in rotation.',
    'Dark web marketplace identified as {orgName} distribution channel for {city} area. 400+ confirmed transactions. Delivery via USPS.',
    'Distribution network assessment: {orgName} controls 60% of {city} fentanyl market. Competing with 2 other organizations for remaining territory.',
  ],

  CARTEL_CONNECTIONS: [
    'Vigil intelligence links {orgName} to Sinaloa Cartel remnant operating across the border. Regular courier traffic identified on I-35 corridor.',
    '{orgName} receiving supply from CJNG-affiliated cell. Wire transfers to Mexican accounts totaling $12M over 6 months. Vigil tracking active.',
    'Cartel connection indirect: {orgName} operating through intermediary network with no direct cartel membership. Wholesale arrangement only.',
    'International connections extend beyond Mexico: {orgName} sourcing directly from Chinese fentanyl producers via dark web. Cutting out cartel middlemen.',
    'Vigil assessment: {orgName} is cartel-directed, not independent. Leadership in {city} takes orders from handlers across the border.',
  ],

  STASH_LOCATIONS: [
    'Vigil surveillance identifies 3 stash houses in {city}: residential property (primary), storage unit (overflow), and commercial garage (vehicle staging).',
    'Thermal imaging and Vigil drone surveillance confirm narcotics processing at industrial property in {city}. Chemical signatures consistent with fentanyl cutting.',
    'Stash location compromised: {orgName} relocating inventory from {city} primary site. Vigil tracking 2 vehicles believed to be carrying product.',
    '5 storage locations mapped across {city}. {orgName} rotates inventory weekly. Vigil GPS tracking on 2 vehicles provides real-time location updates.',
    'Underground stash location identified beneath auto repair shop in {city}. Vigil ground-penetrating radar survey confirms subterranean modifications.',
  ],

  // --- Corporate Espionage ---

  CORPORATE_TARGET: [
    'Target company identified: defense contractor in {city} developing classified weapons systems. {orgName} operative embedded in engineering division.',
    'Vigil intelligence indicates {orgName} targeting pharmaceutical company in {city}. Research valued at $2B. Espionage campaign active for 18+ months.',
    'Target: semiconductor manufacturer in {city} producing chips for military applications. {orgName} conducting social engineering against 3 employees.',
    'Aerospace firm in {city} targeted by {orgName}. Vigil intercepts confirm interest in propulsion technology with dual-use military applications.',
    'Energy company in {city} developing next-generation battery technology. {orgName} attempting to acquire trade secrets via compromised employee.',
  ],

  TRADE_SECRETS: [
    'Trade secrets targeted include weapons guidance system algorithms and manufacturing processes. Classification: TS/SCI. Economic value: $4-8B.',
    'Vigil assessment: {orgName} targeting proprietary AI training datasets and model architectures. Theft would eliminate 5-year competitive advantage.',
    'Pharmaceutical research data targeted: drug compound formulations and clinical trial results. Estimated value: $1.2B in R&D costs.',
    'Semiconductor fabrication process details being exfiltrated. Vigil assesses this would allow foreign state to replicate 3nm chip production capability.',
    'Targeted trade secrets include battery chemistry formulations and manufacturing techniques. Dual-use: commercial and military applications.',
  ],

  OPERATIVE_COVER: [
    '{orgName} operative embedded as visiting researcher at {city} institution. Cover identity: academic from allied nation. Credentials fabricated but convincing.',
    'Operative using cover as management consultant with legitimate contract at target firm. Vigil background check reveals inconsistencies in employment history.',
    'Subject posing as joint venture partner representative in {city}. Cover company is foreign state front. Vigil corporate analysis confirmed.',
    'Operative cover: IT contractor with physical access to target company network. Hired through staffing agency with no connection to {orgName} on paper.',
    '{orgName} using non-traditional collector: recruited US citizen employee with financial vulnerabilities. No foreign operative on-site.',
  ],

  CLIENT_STATE: [
    'Vigil attribution: espionage operation directed by Chinese Ministry of State Security. {orgName} is assessed as MSS front company operating from {city}.',
    'Client state identified as Russia. SVR directing operation through {orgName} intermediary. Intelligence requirements match known Russian collection priorities.',
    'Attribution: Iranian MOIS. {orgName} operational infrastructure overlaps with 2 previous Iranian espionage campaigns in {country}.',
    'Vigil assesses North Korean RGB as client state. {orgName} operating as cut-out. Revenue from stolen IP would fund weapons programs.',
    'Client state unclear. Multiple indicators point to allied nation conducting economic espionage. Vigil coordination with counterintelligence ongoing.',
  ],

  // --- Hostage ---

  HOSTAGE_LOCATION: [
    'Vigil drone surveillance confirms hostage location: commercial building in {city} industrial district. Thermal imaging identifies 8-12 heat signatures. Perimeter security minimal.',
    'Hostage site located in residential area of {city}. Vigil SIGINT triangulation confirmed by ISR overflight. Three-story structure, hostages believed held on second floor.',
    'CCTV network in {city} captured hostage transfer to current location. Vigil has established persistent surveillance. Building egress points mapped.',
    'Vigil geolocation places hostages in a warehouse complex east of {city}. Satellite imagery confirms vehicle activity consistent with captor movement patterns.',
  ],

  HOSTAGE_COUNT: [
    'Vigil assesses 3-5 hostages based on SIGINT voice analysis. At least 2 confirmed US nationals. One hostage identified as a minor.',
    'Confirmed hostage count: 6 individuals. Vigil biometric matching identifies 2 US citizens, 1 allied national, 3 local nationals.',
    'SIGINT intercept from hostage site indicates 4 hostages. One has been identified as a federal employee with TS clearance. Vigil flagging as high-priority.',
    'Vigil estimates 8-10 hostages. Multiple families including children. Exact identification pending — communications from inside are intermittent.',
  ],

  HOSTAGE_CONDITION: [
    'Limited information. Last SIGINT intercept suggests hostages are alive. Captors discussing medical needs for one hostage — possible injury during seizure.',
    'Vigil assessment: hostages are alive but deteriorating. Audio analysis detects elevated stress markers. One hostage may require medical intervention within 24 hours.',
    'Hostage condition: UNKNOWN. No direct communication with hostages. Captor demands suggest hostages remain alive. Time pressure increasing.',
    'Vigil audio intercept confirms hostages are alive and communicating. Morale appears low but no immediate medical emergencies detected.',
  ],

  CAPTOR_ID: [
    'Lead captor identified via Vigil facial recognition: known associate of {orgName}. Criminal record includes prior kidnapping and weapons offenses in {city}.',
    'Captors identified as members of {orgName}. Vigil database cross-reference confirms 3 of 5 are on federal watchlists. Prior military training suspected.',
    'Captor identification: primary subject is {orgName} cell leader. 2 accomplices identified. 1-2 unknown subjects remain unidentified.',
    'Vigil has identified the lead captor through phone intercepts. Subject has no prior criminal record — radicalization appears recent. Unpredictable.',
  ],

  CAPTOR_DEMANDS: [
    'Captors demanding release of 12 federal prisoners. Vigil assesses demands are non-negotiable cover for actual objective: safe passage out of {city}.',
    'Demands communicated via encrypted messaging: $50M ransom and withdrawal of federal agents from {city}. Vigil assesses captors are escalating.',
    'No coherent demands issued. Vigil psychological profiling suggests captors may be ideologically motivated with no interest in negotiation. High risk of execution.',
    'Captors demand media access and public broadcast of manifesto. Vigil assesses this as a propaganda operation. Hostage safety is secondary to captors\' messaging objectives.',
  ],

  ENTRY_POINTS: [
    'Vigil ISR identifies 4 entry points: main entrance (reinforced), rear loading dock (vulnerable), rooftop access (helicopter viable), basement utility tunnel.',
    'Building layout obtained from {city} municipal records. Three viable entry vectors identified. Vigil recommends simultaneous breach on north and east sides.',
    'Thermal imaging reveals interior layout: hostages confined to single room, guards rotating between 2 positions. Optimal breach point: west-facing windows.',
    'Vigil ground-penetrating radar survey of building in {city} reveals utility access corridor beneath street level. Covert approach viable.',
  ],

  // --- Assassination / HVT (Domestic) ---

  LEGAL_AUTHORITY: [
    'Vigil legal analysis: target designated under Executive Order 14XXX as imminent national security threat. Lethal authority authorized by POTUS finding. FISA Court notified.',
    'Legal authority: federal arrest warrant issued. Target has evaded arrest 3 times. Vigil recommends escalation to lethal force authorization given demonstrated evasion capability.',
    'Legal status: target has been placed on classified disposition matrix by interagency review. Vigil confirms all legal prerequisites met. Authority: Title 50.',
    'WARNING: Legal authority ambiguous. Target is a US citizen on US soil. Vigil assesses that lethal action would require presidential finding under EO 12333. Recommend capture if feasible.',
    'Vigil legal review: target qualifies for targeted action under imminent threat doctrine. Multiple failed arrest attempts documented. Attorney General has signed authorization.',
  ],

  COLLATERAL_RISK: [
    'Vigil ISR assessment: target location is residential neighborhood in {city}. 12-15 civilians within blast/engagement radius. Collateral risk: HIGH.',
    'Collateral damage assessment: target operates from a commercial area. Vigil estimates 3-5 bystanders during typical engagement window. Night operation reduces risk to LOW.',
    'Target location is isolated — rural property outside {city}. No civilian structures within 500m. Collateral risk: MINIMAL. Night approach via unpaved road.',
    'Vigil assessment: target frequents crowded public locations in {city}. Engagement during normal hours carries EXTREME collateral risk. Recommend vehicle-based interception on transit route.',
  ],

  ESCAPE_ROUTES: [
    'Vigil pattern-of-life analysis identifies 3 prepared escape routes from target location in {city}. Private airstrip 40 minutes south — must be interdicted.',
    'Target has established escape corridor through {city} subway system. 2 vehicles pre-positioned at separate locations. Vigil GPS tracking on both.',
    'Escape routes limited: target location in {city} has 2 road exits. Both are under Vigil surveillance. No private aviation access within 90 minutes.',
    'Target has a go-bag at secondary residence in {city}. Vigil monitoring confirms subject rehearsed evacuation route twice this month. Foreign passport detected.',
  ],

  // --- Capture / Fugitive ---

  HVT_IDENTITY: [
    'Target positively identified by Vigil facial recognition network: {orgName}. Subject is a priority 1 target on the disposition matrix. Current location: {city}.',
    'Vigil biometric database match confirms target identity. Subject known to operate under 4 aliases. Fingerprint match confirmed via latent prints recovered from {city} safe house.',
  ],

  HVT_NETWORK: [
    'Vigil network analysis maps {orgName}\'s organization: 15-20 associates providing logistics, security, and communications support across the {city} area.',
    'Target network includes 3 inner-circle lieutenants, a financial officer, and a 6-person security detail. Vigil has identified all by name.',
    'SIGINT mapping reveals {orgName} communicating with 8 contacts on a rotating basis. 2 contacts are in positions of governmental authority — corruption suspected.',
  ],

  ASSET_LAST_KNOWN: [
    'Asset last transmitted from {city}, {country}. Emergency beacon activated then ceased. Vigil assessing hostile electronic warfare or physical capture.',
    'Last known position: safe house in {city}. Asset missed scheduled contact 36 hours ago. Vigil pattern analysis suggests compromise, not equipment failure.',
  ],

  COMPROMISE_VECTOR: [
    'Vigil assessment: compromise originated from mole within host nation intelligence service. Asset\'s identity was disclosed through liaison channel.',
    'Compromise vector: communications security failure. Asset\'s encrypted device was seized during a routine traffic stop in {city}. Cover identity exposed.',
    'Source reports indicate {orgName} (hostile CI) identified asset through pattern-of-life analysis. Asset\'s regular meetings with case officer were surveilled.',
  ],

  HOSTILE_CI_ACTIVITY: [
    'Vigil SIGINT detects surge in hostile counterintelligence activity in {city}. Multiple surveillance teams deployed. Checkpoints established on major routes.',
    'Hostile CI activity: HIGH. Security services conducting sweep operations across {city}. Vigil intercepts confirm search specifically targeting foreign intelligence operatives.',
  ],

  EXFIL_ROUTES: [
    'Vigil has mapped 3 exfiltration routes from {city}: overland to border crossing (18h), maritime extraction from port (6h), covert air pickup at coordinates TBD.',
    'Primary exfil route through {city} is compromised — hostile checkpoints on all major highways. Secondary: covert maritime extraction from fishing village 40km south.',
  ],

  ASSET_CONDITION: [
    'Last report indicates asset is mobile but injured. Evading hostile surveillance in {city}. Has access to emergency funds and one backup identity document.',
    'Asset condition: UNKNOWN. No communication for 48 hours. Vigil assessing whether asset has been captured or is maintaining radio silence for security.',
    'Asset is alive and evading. Last dead-drop message indicates subject is sheltering with a local contact in {city}. Hostile CI is searching the area.',
  ],

  COVER_STATUS: [
    'Cover identity is fully compromised. Asset\'s real name and agency affiliation are known to hostile CI. No viable cover for continued operations.',
    'Partial compromise: hostile CI suspects asset but has not confirmed identity. Cover may hold for 24-48 hours if asset avoids known associate locations in {city}.',
  ],

  SAFE_HOUSE_NETWORK: [
    'Vigil maintains 2 emergency safe houses in {city}. House Alpha status: GREEN (uncompromised). House Bravo status: AMBER (possible hostile surveillance detected).',
    'Safe house network in {city}: 3 locations available. Asset must reach the nearest within 6 hours before hostile CI closes the cordon.',
  ],
};

// --- Domestic Intel Value Generation ---
// Picks from domestic pools with placeholder substitution.
// Falls back to generateIntelValue() for non-domestic keys.

function generateDomesticIntelValue(fieldKey, location, orgName) {
  var pool = DOMESTIC_INTEL_VALUE_POOLS[fieldKey];
  if (!pool || pool.length === 0) {
    return generateIntelValue(fieldKey, location, orgName);
  }

  var val = pick(pool);
  if (location) {
    val = val.replace(/\{city\}/g, location.city || '?');
    val = val.replace(/\{country\}/g, location.country || '?');
  }
  val = val.replace(/\{orgName\}/g, orgName || 'unknown organization');
  return val;
}

// --- Domestic Threat Feed Descriptions ---
// Displayed in the feed when a domestic threat spawns.
// Tone: Orwellian surveillance state monitoring its own citizens.

var DOMESTIC_THREAT_DESCRIPTIONS = {
  DOMESTIC_EXTREMISM: [
    'Vigil surveillance network has flagged anomalous activity in {city}. Pattern analysis indicates domestic extremist cell organizing under the banner of {orgName}. Communications intercepts reveal anti-government rhetoric escalating toward operational planning. Monitoring assets deployed.',
    'PRISM intercept: encrypted communications from {city} match linguistic signatures of domestic extremist movement. Vigil has identified {orgName} as the organizing entity. Membership estimated at 8-15 individuals. Automated threat assessment: ELEVATED.',
    'Vigil behavioral algorithms have flagged a cluster of citizens in {city} exhibiting radicalization indicators. Social media surveillance, financial monitoring, and travel pattern analysis converge on {orgName}. Preemptive investigation authorized.',
  ],
  FINANCIAL_CRIME: [
    'Vigil financial surveillance has detected anomalous transaction patterns in {city}. Automated analysis indicates a sophisticated money laundering operation conducted through {orgName}. FinCEN reporting thresholds systematically circumvented. Investigation priority: HIGH.',
    'Federal banking monitors flagged structured deposits across {city} metropolitan area. Vigil traces converge on {orgName}. Shell company network spans 6 jurisdictions. Estimated illicit volume: $15-40M annually.',
    'Vigil algorithmic audit of corporate registrations in {city} identified {orgName} as the nexus of a financial fraud network. Beneficial ownership deliberately obscured. Automated referral to Financial Crimes task force.',
  ],
  CYBER_INTRUSION: [
    'Vigil network defense perimeter has detected unauthorized access attempts against federal infrastructure originating from {city}. Attack signatures attributed to {orgName}. Sophistication level suggests organized capability. Cyber command notified.',
    'Intrusion detected: {orgName} has breached a classified network segment. Initial access vector traced to {city}. Vigil automated containment engaged. Adversary persistence mechanisms identified on 3 hosts. Damage assessment underway.',
  ],
  INSIDER_THREAT: [
    'Vigil insider threat detection system has flagged anomalous behavior by a cleared individual in {city}. Designating as {orgName}. Access patterns, financial indicators, and behavioral analysis exceed threat thresholds. Continuous monitoring authorized.',
    'ALERT: Vigil access monitoring detected unauthorized classified document retrieval by cleared personnel in {city}. Subject designated {orgName}. 340% deviation from baseline access patterns. Counterintelligence investigation initiated.',
    'Vigil behavioral algorithm has identified a potential insider threat operating from a sensitive facility in {city}. Subject designated {orgName}. Indicators include unexplained wealth, foreign travel, and after-hours facility access.',
  ],
  ORGANIZED_CRIME: [
    'Vigil surveillance network has identified an organized criminal enterprise operating in {city}. Entity designated {orgName}. Activities include racketeering, extortion, and narcotics distribution. RICO investigation parameters met.',
    'Law enforcement intelligence fused with Vigil monitoring data confirms {orgName} expanding operations in {city}. Territory disputes with rival organizations increasing violence metrics. Civilian safety assessment: AT RISK.',
  ],
  CIVIL_UNREST: [
    'Vigil social monitoring has detected coordinated protest mobilization in {city}. Organization: {orgName}. Participation models project 2,000-5,000 individuals. Rhetoric analysis indicates anti-government sentiment. Public order threat assessment: ELEVATED.',
    'ALERT: {orgName} is organizing mass demonstrations in {city} targeting federal surveillance programs. Vigil sentiment analysis detects hostile intent toward government institutions. Crowd control and monitoring assets pre-positioned.',
    'Vigil has flagged {orgName} as a domestic movement of concern in {city}. Communications intercepts reveal plans for sustained civil disruption. Foreign amplification of messaging detected on social media platforms.',
  ],
  WHISTLEBLOWER: [
    'Vigil information security monitoring has detected potential unauthorized disclosure of classified material originating from {city}. Designating as {orgName}. Leak channel identified. Containment protocols activated.',
    'CRITICAL: {orgName} — Vigil has identified an active leak of classified operational details. Source traced to {city} facility. Material includes sensitive program information. Publication timeline may be imminent. Damage limitation priority: MAXIMUM.',
    'Vigil automated document tracking system flagged classified material accessed outside normal parameters in {city}. Investigation designated {orgName}. Subject has made contact with media representatives. Interception authorized.',
  ],
  CORPORATE_ESPIONAGE: [
    'Vigil counterintelligence monitoring has detected a foreign-directed economic espionage operation in {city}. Front entity: {orgName}. Target: defense-adjacent technology firm. Trade secret theft in progress.',
    'Vigil network analysis reveals {orgName} operating as a front for foreign intelligence collection in {city}. Corporate espionage campaign targeting critical technology sectors. FBI counterintelligence coordination initiated.',
  ],
  NARCOTICS_NETWORK: [
    'Vigil interdiction intelligence has identified a major narcotics distribution network in {city}. Entity: {orgName}. Supply chain mapped from border crossing to street-level distribution. DEA task force coordination authorized.',
    'Drug trafficking network {orgName} expanding operations in {city}. Vigil monitoring detects fentanyl distribution volume increasing 200% over baseline. Overdose mortality data correlates with network activity. Threat to public safety: CRITICAL.',
    'Vigil surveillance has mapped {orgName} distribution infrastructure across {city}. 22 distribution points, 4 stash houses, and a processing facility identified. Coordinated takedown planning initiated.',
  ],
  DOMESTIC_TERROR: [
    'ALERT: Vigil threat detection has identified an active domestic terror cell in {city}. Designating as {orgName}. SIGINT indicates advanced attack planning. Target selection phase underway. Preemptive action authorized.',
    'Vigil has intercepted communications indicating {orgName} is preparing a domestic terror operation in {city}. Materials acquisition detected. Timeline assessment: 2-4 weeks to operational capability. Threat level: CRITICAL.',
    'Domestic terror threat: {orgName} identified in {city} through convergence of SIGINT, financial monitoring, and behavioral analysis. Cell structure mapped. Vigil recommends immediate disruption before operational phase.',
  ],
  HOSTAGE_DOMESTIC: [
    'HOSTAGE SITUATION: Vigil monitoring has detected a hostage-taking in progress in {city}. Armed subjects have seized civilians at a commercial location. Designating as {orgName}. FBI HRT and local SWAT notified. Vigil establishing persistent surveillance.',
    'ALERT: Multiple hostages seized in {city}. Subjects identified as {orgName}. Demands being communicated to local law enforcement. Vigil is providing real-time SIGINT and ISR support. Tactical response authorization requested.',
    'Vigil CCTV network has captured an armed hostage-taking at a facility in {city}. At least 4 hostages confirmed. Subject designated {orgName}. Vigil behavioral analysis indicates high risk of violence. Immediate tactical intervention may be required.',
  ],
  ASSASSINATION_TARGET: [
    'Vigil has identified a high-priority domestic target requiring elimination in {city}. Subject designated {orgName}. Target presents an imminent national security threat based on intelligence intercepts. Legal authority review underway. Operational planning authorized.',
    'CLASSIFIED — DISPOSITION MATRIX: {orgName} has been designated for targeted action in {city}. Subject has evaded 3 prior federal arrest attempts and continues to direct operations that threaten national security. Vigil recommends lethal or capture options.',
    'Vigil intelligence assessment: {orgName} in {city} represents a clear and present danger. Subject\'s activities have directly resulted in loss of life and compromise of classified programs. Standard law enforcement approaches have failed. Escalated response authorized.',
  ],
  DOMESTIC_CAPTURE_TARGET: [
    'FUGITIVE ALERT: Vigil monitoring has located a high-priority federal fugitive in {city}. Designated {orgName}. Subject has outstanding federal warrants across multiple jurisdictions. US Marshals coordination initiated.',
    'Vigil facial recognition network has identified {orgName} in {city}. Subject is a priority fugitive who escaped federal custody 47 days ago. Armed and considered extremely dangerous. Apprehension teams being assembled.',
    'CAPTURE TARGET: {orgName} — a high-value domestic subject — has been located in {city} through Vigil surveillance network analysis. Subject possesses critical intelligence and must be taken alive. Federal warrant in hand. Tactical arrest planning authorized.',
  ],
};
